/* tslint:disable */
/* eslint-disable */
/**
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TemplateFieldSpec } from './TemplateFieldSpec';
import {
    TemplateFieldSpecFromJSON,
    TemplateFieldSpecFromJSONTyped,
    TemplateFieldSpecToJSON,
    TemplateFieldSpecToJSONTyped,
} from './TemplateFieldSpec';

/**
 * For array fields: spec defining the structure of each item
 * @export
 * @interface Spec
 */
export interface Spec {
    /**
     * Field name
     * @type {string}
     * @memberof Spec
     */
    name: string;
    /**
     * Field label
     * @type {string}
     * @memberof Spec
     */
    label: string;
    /**
     * Field type: text, number
     * @type {string}
     * @memberof Spec
     */
    type?: string;
}

/**
 * Check if a given object implements the Spec interface.
 */
export function instanceOfSpec(value: object): value is Spec {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    return true;
}

export function SpecFromJSON(json: any): Spec {
    return SpecFromJSONTyped(json, false);
}

export function SpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): Spec {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'label': json['label'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function SpecToJSON(json: any): Spec {
    return SpecToJSONTyped(json, false);
}

export function SpecToJSONTyped(value?: Spec | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'label': value['label'],
        'type': value['type'],
    };
}

