/* tslint:disable */
/* eslint-disable */
/**
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Spec } from './Spec';
import {
    SpecFromJSON,
    SpecFromJSONTyped,
    SpecToJSON,
    SpecToJSONTyped,
} from './Spec';

/**
 * Field definition for template variables (compatible with Zapier and Make.com)
 * @export
 * @interface TemplateField
 */
export interface TemplateField {
    /**
     * Field key/identifier
     * @type {string}
     * @memberof TemplateField
     */
    key: string;
    /**
     * Human-readable label
     * @type {string}
     * @memberof TemplateField
     */
    label: string;
    /**
     * Field type: string, integer, number, boolean, array
     * @type {string}
     * @memberof TemplateField
     */
    type?: string;
    /**
     * Whether the field is required
     * @type {boolean}
     * @memberof TemplateField
     */
    required?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TemplateField
     */
    helpText?: string | null;
    /**
     * 
     * @type {Spec}
     * @memberof TemplateField
     */
    spec?: Spec | null;
}

/**
 * Check if a given object implements the TemplateField interface.
 */
export function instanceOfTemplateField(value: object): value is TemplateField {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    return true;
}

export function TemplateFieldFromJSON(json: any): TemplateField {
    return TemplateFieldFromJSONTyped(json, false);
}

export function TemplateFieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplateField {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'label': json['label'],
        'type': json['type'] == null ? undefined : json['type'],
        'required': json['required'] == null ? undefined : json['required'],
        'helpText': json['helpText'] == null ? undefined : json['helpText'],
        'spec': json['spec'] == null ? undefined : SpecFromJSON(json['spec']),
    };
}

export function TemplateFieldToJSON(json: any): TemplateField {
    return TemplateFieldToJSONTyped(json, false);
}

export function TemplateFieldToJSONTyped(value?: TemplateField | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'label': value['label'],
        'type': value['type'],
        'required': value['required'],
        'helpText': value['helpText'],
        'spec': SpecToJSON(value['spec']),
    };
}

